---
title: "*Hydrological processes quiz"
author: Back to [course overview](../index.html#hydrological-processes)
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    ratio: 16x10
    theme: material
    lib_dir: ../
---

# Your quiz!

## Trond
> - **How much water does a big birch tree “drink” during a hot summers day?**
> - circa 400 liters
> - **In what ways can forest reduce flooding and the damages it prevents?**
> - Keep the riverbed in place and shape. Prevent obsticales from creating further damage, filtering out rocks, debris and floating trees. Slowing down the water, reducing the energy in the flood. takes up water


## Jan  Zeiß
> - **How are Dolines created?**
> - Dolines appear in karst aquifiers. Over time the water dissolves the limestone and creates cave systems. If the caves are close to the surface they can collapse, creating cone shaped depressions that are called Dolines.

## Jan  Zeiß
> - **What are the impacts of deforestation in Australia regarding groundwater and soil properties?**
> - Deforestation causes higher evaporation rates. Consequently groundwater is not infiltrating the soil anymore but is moving upwards in the soil, transporting salt from the deeper layers to the top causing salinization of the soil.

## Christian
> - **what  is  the  differrence  between  gaining  streams  and  loosing  streams?**
> - A  gaining  stream  lies  below  the  ground  water  table  and  is  supplied  from  it  and  a  loosing  streams  lies  above  the  groundwater  table  and  supplies  the  ground  water
> - **Which  grain  size  has  the  highest  porosity  and  has  it  also  the  highest  permeability?**
> - Clay  has  the  highest  porosity  but  the  lowest  permeability.
> - **What  are  the  particularities  of  cloud  forests  in  terms  of  hydrology?**
>  -  Cloud  forest  in  such  high  latitudes  that  they  are  almost  permanently  in  the  cloud  layer  and  the  trees  gain  much  more  water  direct  from  the  cloud  and  deliver  it  through  into  the  soil  than  it  would  be  delivered  in  that  regions  without  the  forests.   Where  those  occur  those  are  often  the  most  important  source  of  drinking  water.



## Håkon the mad

> - **Why is planet earths water an increasingly important topic for earths life?**
> - Because, the availability and quality of clean water in many regions of the earth is threatened by overuse, misuse and pollution by humans.

> - **What are the pros and cons of a forest, compared to a plain, in relation to water supply?**
> - Forest: Pro: Cleaner water, less erosion, less sediments, minerals, flood controll. Con: Allows less water to be supplied downstream; disrupts precipitation with canopy, evaporation from foliage, and transpiration. Plain: pro: Larger supply of water downstream, more flow above ground. Con: Dirtier water, more erosion, more sediments.

## Håkon the mad
> - **What is the goldilocks zone around the sun and why is it significant for life on earth?**
> - The goldilocks zone is the distance to the sun which allows water to be present in all three states, as ice, liquid and gas. Earth is within this zone, and all life and climate on earth has based itself on water, powered by the sun. Water is like the blood flowing through the muscles and tissues of life, held by the skeleton earth, fed by the sun.

## Jostein

## Simen
> - **How much does the available water content change in a soil when Humus is added as opposed to not present?**

> - 4 times to 1.75 times higher

## Simen

> - **What is it called when rain drops hit Threes rather than ground on their way down?**

> - Interception

> - **What happens to the infiltration rates when you get closer to trees?**

>- It increases

## Calum
> - **San Antonio water supply - Edwards Aquifer. Primary source of water for San Antonio , 8th Largest city in US. It is a highly permeable aquifer - recharge of aquifer is very fast - especially through the presence of sinkholes. What kind of aquifer is this likely to be? Does anyone know a distinctive feature of this particular aquifer which makes the chemical quality of the water change abruptly across a short distance?**
> - It is a permeable Karst Aquifer made up of partially dissolved limestone. A fault zone runs across the aquifer which can change chemical quality of water - saline-water line. 


## Matias
> - **End moraines usually don't contain much water. Looking at a forested area, how can you recognize end moraines?**
> - End moraines are usually covered with Scots pine, and the surrounding area is often covered with other forest. Scots pine has long roots that go deeper to find water.

## Matias
> - **What is the wettest forest in Northern Europe?**
> - The forest in Doggerland, flooded land in the Northsea

## Matias
> - **How deep goes the deepest reported root?**
> -  122 m. Wild Fig tree (ficus) in South Africa


## Tewelde
> - **What is the importance of sustainable forest management?**
> - ensure the supply of good-quality fresh water. provide protection from natural hazards such as flooding or soil erosion and to protect the needs of aquatic species.
> - **How much is the size of forest covered area of Norway?** 
> - 30.7% —or about 9,387,000 hectares—of Norway is forested.
> - **How Much is the average yearly precipitation of Norway with a global rank?**
> - The average yrealy precipitation of Norway is 1,414 (mm per year) with a global rank of 62.

## Rannveig

## Martha
> -  **How can tree canopies reduce groundwater and the streamflow?**
> - through interception of precipitation and evaporation and transpiration from foliage. 

> - **Which services and good can trees and forests give us?**
> - erosion control, improved water quality, carbon fixing, reduced salinization, recreation and aesthetic appeal, timber, fuelwood, biodiversity 


## Anne Marte
> - **What do the people from India think would happen to the rivers if they restore the forests in Himalaya (Nepal)?**
> - The rivers would start flooding again.
> - **What is the safest protection for groundwater?**
> - Forest cover on its sources.


## Victoria
> - **Describe the difference between actual and potential evapotranspiration, and explain the importance in crop production.**
> - Potential evapotranspiration (PE) is a measure of the ability of the atmosphere to remove water from the surface through the processes of evaporation and transpiration assuming NO control on water supply. PE requires energy. The main source of energy is from the sun, and accounts for 80% of the variation in potential evapotranspiration in a given area. Wind is the second main source of energy. The rate of evapotranspiration is controlled by vapour pressure gradients set up between the surface where water is lost (e.g. stomata, leaf surface, ground surface) and humidity of the atmosphere.

## Victoria
> - Actual evapotranspiration is the actual amount of water that is removed from a surface due to the processes of evaporation and transpiration.
> - Crops are grown in areas without sufficient water supply for crop growth, hence management schemes are designed such as irrigation schemes. Irrigation schemes provide necessary supplementary water and is calculated by
> - **Crop water need to achieve maximum growth productivity?**
> - crop water need = potential evapotranspiration - actual evapotranspiration 

## Oliver
> - **What is the main reason trees can use more water than shorter vegetation types?**
> - Mainly due to the interception of rainwater by their aerodynamically rougher canopies.
> - **Which type of forest (coniferous or broadleaf) uses the most water, and why?**
> - They have almost equal transpiration, but the conifers have higher interception because they have their needles all year 
> - **What did the fish say when it swam into a wall?**
> - Dam 


## Bjørnar

> - **Amazonas questions. First see if anyone can anwared without a) b) c)**
> - **How large is the amazon forest? (Km2)**
> - a: 10 250 000 km2
> - b: 5 500 000 km2
> - c: 1 000 900 km2
> - Answer: b
> - **How long is the amazon river and what contries goes it trougth?**
> - a: 6692 km. Contries: Peru, Colombia,Brazil
> - b: 5928 km. Contries: Ecuador,Brazil.
> - c: 5892 km. Contries. Brazil, Peru
> - Answer: a

## Bjørnar
> - **What is the average disharge of the amazon river?**
> - a: 209 m3/s
> - b: 304 m3/s
> - c: 180 m3/s
> - Answer: a
> - b is max, and c is min

## Guro

> - **Why should cloud forests be maintained as forest?**
> - Clous forest are important for water production, erosion control and biodiversity, and generally unsuitable for other sustainable uses.

> - **How many ha of land is affected by salinization inducted by human activities?**
> - 77 million

## Ragnhild