---
title: "Exercises: hydrological processes"
author: Back to [course overview](../index.html#exercise-sessions)
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    ratio: 16x10
    theme: material
    lib_dir: ../
---

# Groundwater recession

## Modelling recession dynamics

$Q = Q_{0} * e^{-ct}$

$c$ is the recession constant.

Groundwater recession would be a function of some (average) measure of hydraulic head:

$Q = f(h(t))$

If the aquifer is 1m wide, has a length L, and a storativity or specific yield S, then we can write:

$SL \frac{dh}{dt} = -q_r = -f(h(t))$

Proportionality between h and qr:

$q_r = cSLh(t)$

and by substituting we get

$\frac{dh}{dt} = -ch$

which then integrated gives:*

$h = h_0 * e^{-ct}$

where h0 is the average hydraulic head at the initial time.
Then from the proportionality relation we have:

$q_r = cSL * h_0 * e^{-ct}$

or 

$Q_r = Q_{r0} * e^{-ct}$

So the use of the first equation implies that the groundwater reservoir behaves as a linear reservoir, the GW outflow is proportional the amount of water stored.

This tool can be usefull to estimate flow throughout a dry season.



<!-- # Hydrological modelling with HBV Light -->

<!-- Follow instruction of [exercise 6: Snow model](http://www.geo.uzh.ch/en/units/h2k/Services/HBV-Model/Exercise-6.html) provided by Universy of Zürich -->

<!-- Download this article: [Teaching hydrological modeling with a user-friendly catchment-runoff-model software package](https://www.hydrol-earth-syst-sci.net/16/3315/2012/) -->

<!-- ## Steps -->

<!-- Load the data into R -->

<!-- Name model parameters and initialize modelled variables -->

<!-- Make a "for" loop to run the model -->


<!-- ## Good of fit metrics -->

<!-- Discuss different ways to assess the quality of your model. -->

<!-- How might different objective functions be used in specific contexts? -->

<!-- Add a goodness of fit measure to your routine and optimize the model according to this metric. -->


<!-- # Extras -->

<!-- ## Irrigation exercise -->

<!-- Good exercise page 255, elements of physical hydrology -->


<!-- ## Prepare potential evapotranspiration series -->

<!-- Use the method of your choice to compute daily potential evapotraspiration. -->

<!-- Try energy balance calculations for potential evapotranspiration. See Elements of physical hydrology. -->

<!-- AirGR can also calculate it with the Oudin’s formula. The function is `Edaily_Oudin()` -->
