---
title: "Hydrological modelling"
author: Back to [course overview](../index.html#exercise-sessions)
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    ratio: 16x10
    theme: material
    lib_dir: ../
---

## Using the hydrological model "HBV Light"

Jan Seibert at University of Zürich provides a model and exercises [there](https://www.geo.uzh.ch/en/units/h2k/Services/HBV-Model.html).

Do all exercises with his data. You can later experiment with data from the Sogndal catchment.

## Hydrological modelling

In this exercise session focusing on the Songdal catchment, we will experiment with various hydrological models:

* Recession from a linear reservoir
* Response to a snowmelt event
* Hydrological extremes for Songdalselvi

The course material is [hydrological processes](./01_hydrology/01_hydrological_processes)

## Data preparation

Download meteorological and hydrological data for the Sogndalselvi catchment.
Which variables do you need?



Hint: you can download data from there: https://www.nve.no/hydrologi/hydrologiske-data/
With this link, snow water equivalent is only available for the past 2 months at Anestoelen
Check Senorge and Xgeo to get longer term data

NVE only has Anestoelen for temperature data. Has Metno more available data?
Download the additional data and discuss temperature lapse rates in the catchment.


## Link between groundwater variation and discharge recession

Experiment with relationships between the drop in groundwater level at Anestoelen during the winter, and the recession in discharge at the outlet of Dalavatnet.

Show that groundwater recession from an unconfined sloping aquifer with a flat bedrock (see sketch) is analog to the emptying of a linear reservoir where Q_out = constant * Volume
page 204, elements of physical hydrology

## Hydrological extremes

Experiment with daily, monthly, yearly precipitation data and see how the probability distribution changes.
