---
title: "Hydraulics: pipes and open channel"
author: Back to [course overview](../index.html#exercise-sessions)
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    ratio: 16x10
    theme: material
    lib_dir: ../
---

## Case study: Jostedal

Use NVE Atlas, Norgeskart, Nevina to find the catchments specific to each water intake in Jostedalen.

What is the mean residence time at water in the Styggevatn reservoir?
What is the mean residence time in the Leirdal reservoir?
Which management problems are linked to the situation in Leirdal?
Discuss how Statkraft can best optimize the Leirdal reservoir

The population was happy that a dam was built in order to control floods (i.e. [1979 flood](https://www.youtube.com/watch?v=9GDCZ-O6UbA)). Statkraft was allowed to built as long as they provided enough extra capacity at all times to cover an exeptional event. The top reservoir is therefore never full.

### Schematics of the hydropower scheme

Think about possible designs of hydropower schemes that least affect the valley and provide good returns.

You can find information on built water infrastructure on the [NVE Atlas].

They decided to tap into numerous side valleys to the east of Jostedalen, directing water towards a power station at the lower end of the valley. Design potential schemes based on this information.

In this [document](https://www.statkraft.no/globalassets/old-contains-the-old-folder-structure/documents/jostedal-official-assessment-final-10-may-2013_tcm9-27383.pdf) you can find a schematic of the design

### Mean water volumes

Use Nevina to calculate the properties of all side catchments flowing into the hydropower infrastructure.

Assuming steady flow conditions, how high would the intake need to be in this side valley?

Calculate how much flow can be achieved in the tunnel

How much flow can be directed from the side-catchments back to the main reservoir by gravity.
Will one of the side intake need a non-return valve to avoid a backflow through the intake?
Experiment with the behavior of those intakes during various events: intense hourly precipitation, big daily events...

### Specific considerations for extreme events

Do you know other places where hydropower projects have been suggested to help mitigate flooding?
Odda

Use NVE Atlas, Norgeskart, Nevina to find the catchments specific to each water intake in Jostedalen.

Calculate much flow can be achieved in the tunnel

How much flow can be directed from the side-catchments back to the main reservoir by gravity.
Will one of the side intake need a non-return valve to avoid a backflow through the intake?
Experiment with the behavior of those intakes during various events: intense hourly precipitation, big daily events...


### Reconstructing the 1979 flood

[Statkraft presentation of the Jostedalen hydropower scheme](https://www.statkraft.com/energy-sources/Power-plants/Norway/Jostedal/)

[Statkraft is seeking new consessions on the western side of Jostedalen](https://www.statkraft.no/media/pressemeldinger/Pressemeldinger-arkiv/2012/statkraft-skrinlegger-overforing-av-vestsideelvene-i-jostedalen/)


Information on [Nigardsbreen](https://www.nve.no/hydrologi/bre/bremalinger/massebalansemalinger/nigardsbreen)


Calculate how much inflow can be expected into the Styggevatnet reservoir during the melt season.
You can base yourself on this [document](http://publikasjoner.nve.no/rapport/2017/rapport2017_76.pdf), which present recent mass balance measurements at Austdalsbreen and Nigardsbreen.

Why do you think there is such a big difference in mass balance between Nigardsbreen and Austdalsbreen?

## Stream bank reinforcement in L?rdal

During the 2014 floods, the stream coming out of XX found a new flowpath and destroyed some agricultural land.
Which measure would you suggest to avoid such an event in the future?

NVE decided to build a riprap protection on the stretch of stream bank affected.
Discuss the potential location of this riprap and calculate its necessary height to protect against a 200 year flood.
Hint: [Nevina](www.nevina.nve.no) helps you define the catchment area and the 200-year flood.
Hint: The riprap protection will have a very controlled geometry, making it easy to use open channel formulas.
Hint: For a quite precise measure of steepness, you can use [hoydedata.no](www.hoydedata.no).

What are potential negative downstream impacts of such a measure?

Have a good look at the map in Norgeskart and try to find upstream features that could bring accrued sediments downstream.
Hint: The L?rdal tunnel is not far.

## Manning's equation
Replacing the last expression for $C$ into Chézy's equation yields:

\[V = {\frac{R_h^{2/3} S^{1/2}}{n}} \]

$V$ is the cross-sectional average velocity

$n$ is the Manning coefficient. (in $s*m^{-\frac {1}{3}}$)

$R_h$ is the hydraulic radius in meters

$S$ is the gradient in hydraulic head, which is the channel bed slope when the water depth is constant

## Typical Manning roughness coefficients
According to "Elements of physical hydrology"

Channel material	| Manning's n
--- | ---
Glass	| 0.01	
Smooth concrete	|	0.012
Earth canal | 0.02
Natural streams | 0.024-0.075

## Application

Manning coefficient: $n = 0.025$
Hydraulic radius: $R_h$ ?
Cross sectional area / Wetted perimeter = x*10 / (2x + 20)

## Further reading

Methodology for the glacier mass balance assessments: [Reanalysis of long-term series of glaciological and geodetic mass balance for 10 Norwegian glaciers](https://www.the-cryosphere.net/10/535/2016/tc-10-535-2016.pdf)

This [NVE report in Norwegian](http://publikasjoner.nve.no/hydra/rapport/mi05.pdf) presents erosion in Norway, with some information on Jostedalen
    