---
title: "Urban and rural catchments"
author: Back to [course overview](../index.html#exercise-sessions)
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    ratio: 16x10
    theme: material
    lib_dir: ../
---

## Case study: Oslo?

https://www.nve.no/flaum-og-skred/fagsamlinger-2018-2019/

## Residential project in Leikanger

A residential development for 100 houses is planned here. Discuss the existing hydrological condition.
Are there existing streams running through the property?
How easy is it to define their respective catchments?
which risks might become more accute in such catchments with climate change?
Design a first rough outline of the development in terms of roads, house and stormwater infrastructure.
What is the impact of your design?
Which physical / social / economical constraints did you take into account?

Estimate what could be a 20 and a 200-year flood for the stream on the eastern boundary.
Estimate the additional flow your initial flow development plan would add to those storm flows.
Discuss alternative designs that would minimize this.
Be creative: you can draw, add off-the-grid or agricultural features. 


Calculate the impact on downstream runoff of a new development and try to minimize this impact.
Design the on-site retention measures for the mean flood
Estimate the concentration time and choose the design rain event accordingly.
Design the development-scale retention / infiltration measures for the 20-year flood
Provide safe flow paths for the 200-year flood.

## Case study in Sandane

Should this be an excursion, something to read at home and then an exercise session?
http://webfileservice.nve.no/API/PublishedFiles/Download/201707426/2314351
all presentation from the NVE conference there:
https://www.nve.no/flaum-og-skred/fagsamlinger-2018-2019/foredrag-fra-fagsamlingene/

they have the option to flood their football filled. Quantify how useful this could be for different flood events.

Evaluate the volume of water than can be stored in the football field. How to control the flow out of this temporary reservoir?

